# Generated by Django 3.2.6 on 2021-08-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
